name: C. Anderson Johnson (Andy)
favicon: null
layout_spectrum: 0.24739055195823312
typography_spectrum: 0.30988596263341606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42377962241880596
  lightness: 0.5824327832087874
  saturation: 0.8246044274419546
  rhythmicContrast: 0.08220874168910086
purpose: []
